/*
-------------------------------------------
Daher Engine
------------

	$Author: Daher Alfawares $
	$Revision: 1.3 $
	$Date: 2004/07/31 19:22:00 $
	$Id: DGL.H,v 1.3 2004/07/31 19:22:00 Daher Alfawares Exp $
	$Name:  $

	Copyright (c) 2004, Daher Alfawares
-------------------------------------------
*/


#ifndef ___DGL_H
#define ___DGL_H



#include "DShared.h"

// DGL main
#include "DGL_Main.h"

// DGL utilities
#include "DGL_Texture.h"
#include "DGL_Frustum.h"
#include "DGL_Extensions.h"

// basic
#include "DGL_Color.h"
#include "DGL_Vertex.h"
#include "DGL_Matrix.h"
#include "DGL_Light.h"
#include "DGL_State.h"

// font
#include "DGL_Font.h"
#include "DGL_Font3D.h"

// effects
#include "DGL_FX.h"
#include "DGL_FadeScreen.h"
#include "DGL_Fog.h"
#include "DGL_Blur.h"
#include "DGL_Particle.h"
#include "DGL_Avi.h"
#include "DGL_TextImage.h"

// collision
#include "DGL_Ball.h"

// camera
#include "DGL_Camera.h"

// train
#include "DGL_Train.h"

// loading screen
#include "DGL_Loadingscreen.h"

// shader library
#include "DGL_Shader.h"

// models
#include "DGL_Model.h"	// base class
#include "DGL_Modelmilkshape.h"

// tomas hamala's model
#include "DGL_Tomas_Model.h" // base class
#include "DGL_Tomas_M3ds.h"

// terrain
#include "DGL_Terrain.h"
#include "DGL_Skybox.h"
#include "DGL_Water.h"


#endif // ___DGL_H